# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:00:25+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Message(BaseModel):
    text: Optional[str] = None
    time: Optional[int] = None
    userId: Optional[str] = None
    userName: Optional[str] = None


class SessionInfo(BaseModel):
    authorID: Optional[str] = None
    groupID: Optional[str] = None
    id: Optional[str] = None
    validUntil: Optional[int] = None


class UserInfo(BaseModel):
    colorId: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    timestamp: Optional[int] = None


class AppendChatMessageGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class AppendChatMessageGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class AppendChatMessageGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class AppendChatMessageGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class AppendChatMessagePostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class AppendChatMessagePostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class AppendChatMessagePostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class AppendChatMessagePostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class AppendTextGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class AppendTextGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class AppendTextGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class AppendTextGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class AppendTextPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class AppendTextPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class AppendTextPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class AppendTextPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CheckTokenGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CheckTokenGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CheckTokenGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CheckTokenGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CheckTokenPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CheckTokenPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CheckTokenPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CheckTokenPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CopyPadGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CopyPadGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CopyPadGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CopyPadGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CopyPadPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CopyPadPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CopyPadPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CopyPadPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CopyPadWithoutHistoryGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CopyPadWithoutHistoryGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CopyPadWithoutHistoryGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CopyPadWithoutHistoryGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CopyPadWithoutHistoryPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CopyPadWithoutHistoryPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CopyPadWithoutHistoryPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CopyPadWithoutHistoryPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data(BaseModel):
    authorID: Optional[str] = None


class CreateAuthorGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateAuthorGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateAuthorGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateAuthorGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateAuthorPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateAuthorPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateAuthorPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateAuthorPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateAuthorIfNotExistsForGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateAuthorIfNotExistsForGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateAuthorIfNotExistsForGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateAuthorIfNotExistsForGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateAuthorIfNotExistsForPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateAuthorIfNotExistsForPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateAuthorIfNotExistsForPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateAuthorIfNotExistsForPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateDiffHTMLGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateDiffHTMLGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateDiffHTMLGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateDiffHTMLGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateDiffHTMLPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateDiffHTMLPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateDiffHTMLPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateDiffHTMLPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data4(BaseModel):
    groupID: Optional[str] = None


class CreateGroupGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data4] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateGroupGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateGroupGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateGroupGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateGroupPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data4] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateGroupPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateGroupPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateGroupPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateGroupIfNotExistsForGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data4] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateGroupIfNotExistsForGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateGroupIfNotExistsForGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateGroupIfNotExistsForGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateGroupIfNotExistsForPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data4] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateGroupIfNotExistsForPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateGroupIfNotExistsForPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateGroupIfNotExistsForPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateGroupPadGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CreateGroupPadGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateGroupPadGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateGroupPadGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateGroupPadPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CreateGroupPadPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateGroupPadPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateGroupPadPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreatePadGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CreatePadGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreatePadGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreatePadGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreatePadPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class CreatePadPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreatePadPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreatePadPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data8(BaseModel):
    sessionID: Optional[str] = None


class CreateSessionGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data8] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateSessionGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateSessionGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateSessionGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class CreateSessionPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data8] = None
    message: Optional[str] = Field(None, examples=['ok'])


class CreateSessionPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class CreateSessionPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class CreateSessionPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class DeleteGroupGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class DeleteGroupGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class DeleteGroupGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class DeleteGroupGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class DeleteGroupPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class DeleteGroupPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class DeleteGroupPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class DeleteGroupPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class DeletePadGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class DeletePadGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class DeletePadGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class DeletePadGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class DeletePadPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class DeletePadPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class DeletePadPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class DeletePadPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class DeleteSessionGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class DeleteSessionGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class DeleteSessionGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class DeleteSessionGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class DeleteSessionPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class DeleteSessionPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class DeleteSessionPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class DeleteSessionPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetAttributePoolGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetAttributePoolGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetAttributePoolGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetAttributePoolGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetAttributePoolPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetAttributePoolPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetAttributePoolPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetAttributePoolPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Info(BaseModel):
    colorId: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    timestamp: Optional[int] = None


class Data10(BaseModel):
    info: Optional[Info] = None


class GetAuthorNameGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data10] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetAuthorNameGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetAuthorNameGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetAuthorNameGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data11(BaseModel):
    info: Optional[Info] = None


class GetAuthorNamePostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data11] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetAuthorNamePostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetAuthorNamePostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetAuthorNamePostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class ChatHead(BaseModel):
    text: Optional[str] = None
    time: Optional[int] = None
    userId: Optional[str] = None
    userName: Optional[str] = None


class Data12(BaseModel):
    chatHead: Optional[ChatHead] = None


class GetChatHeadGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data12] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetChatHeadGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetChatHeadGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetChatHeadGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data13(BaseModel):
    chatHead: Optional[ChatHead] = None


class GetChatHeadPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data13] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetChatHeadPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetChatHeadPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetChatHeadPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data14(BaseModel):
    messages: Optional[List[Message]] = None


class GetChatHistoryGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data14] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetChatHistoryGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetChatHistoryGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetChatHistoryGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data15(BaseModel):
    messages: Optional[List[Message]] = None


class GetChatHistoryPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data15] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetChatHistoryPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetChatHistoryPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetChatHistoryPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data16(BaseModel):
    html: Optional[str] = None


class GetHTMLGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data16] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetHTMLGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetHTMLGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetHTMLGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetHTMLPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data16] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetHTMLPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetHTMLPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetHTMLPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data18(BaseModel):
    lastEdited: Optional[int] = None


class GetLastEditedGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data18] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetLastEditedGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetLastEditedGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetLastEditedGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetLastEditedPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data18] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetLastEditedPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetLastEditedPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetLastEditedPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetPadIDGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetPadIDGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetPadIDGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetPadIDGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetPadIDPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetPadIDPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetPadIDPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetPadIDPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data20(BaseModel):
    publicStatus: Optional[bool] = None


class GetPublicStatusGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data20] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetPublicStatusGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetPublicStatusGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetPublicStatusGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetPublicStatusPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data20] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetPublicStatusPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetPublicStatusPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetPublicStatusPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data22(BaseModel):
    readOnlyID: Optional[str] = None


class GetReadOnlyIDGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data22] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetReadOnlyIDGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetReadOnlyIDGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetReadOnlyIDGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetReadOnlyIDPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data22] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetReadOnlyIDPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetReadOnlyIDPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetReadOnlyIDPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetRevisionChangesetGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetRevisionChangesetGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetRevisionChangesetGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetRevisionChangesetGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetRevisionChangesetPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetRevisionChangesetPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetRevisionChangesetPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetRevisionChangesetPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data24(BaseModel):
    revisions: Optional[int] = None


class GetRevisionsCountGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data24] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetRevisionsCountGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetRevisionsCountGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetRevisionsCountGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetRevisionsCountPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data24] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetRevisionsCountPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetRevisionsCountPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetRevisionsCountPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetSavedRevisionsCountGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetSavedRevisionsCountGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetSavedRevisionsCountGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetSavedRevisionsCountGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetSavedRevisionsCountPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetSavedRevisionsCountPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetSavedRevisionsCountPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetSavedRevisionsCountPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Info2(BaseModel):
    authorID: Optional[str] = None
    groupID: Optional[str] = None
    id: Optional[str] = None
    validUntil: Optional[int] = None


class Data26(BaseModel):
    info: Optional[Info2] = None


class GetSessionInfoGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data26] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetSessionInfoGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetSessionInfoGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetSessionInfoGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data27(BaseModel):
    info: Optional[Info2] = None


class GetSessionInfoPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data27] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetSessionInfoPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetSessionInfoPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetSessionInfoPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetStatsGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetStatsGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetStatsGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetStatsGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetStatsPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class GetStatsPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetStatsPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetStatsPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data28(BaseModel):
    text: Optional[str] = None


class GetTextGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data28] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetTextGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetTextGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetTextGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class GetTextPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data28] = None
    message: Optional[str] = Field(None, examples=['ok'])


class GetTextPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class GetTextPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class GetTextPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data30(BaseModel):
    groupIDs: Optional[List[str]] = None


class ListAllGroupsGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data30] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListAllGroupsGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListAllGroupsGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListAllGroupsGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class ListAllGroupsPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data30] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListAllGroupsPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListAllGroupsPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListAllGroupsPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data32(BaseModel):
    padIDs: Optional[List[str]] = None


class ListAllPadsGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data32] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListAllPadsGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListAllPadsGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListAllPadsGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class ListAllPadsPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data32] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListAllPadsPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListAllPadsPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListAllPadsPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data34(BaseModel):
    authorIDs: Optional[List[str]] = None


class ListAuthorsOfPadGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data34] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListAuthorsOfPadGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListAuthorsOfPadGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListAuthorsOfPadGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class ListAuthorsOfPadPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data34] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListAuthorsOfPadPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListAuthorsOfPadPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListAuthorsOfPadPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data36(BaseModel):
    padIDs: Optional[List[str]] = None


class ListPadsGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data36] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListPadsGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListPadsGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListPadsGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class ListPadsPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data36] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListPadsPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListPadsPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListPadsPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class ListPadsOfAuthorGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data36] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListPadsOfAuthorGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListPadsOfAuthorGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListPadsOfAuthorGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class ListPadsOfAuthorPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data36] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListPadsOfAuthorPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListPadsOfAuthorPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListPadsOfAuthorPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class ListSavedRevisionsGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class ListSavedRevisionsGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListSavedRevisionsGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListSavedRevisionsGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class ListSavedRevisionsPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class ListSavedRevisionsPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListSavedRevisionsPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListSavedRevisionsPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Session(BaseModel):
    authorID: Optional[str] = None
    groupID: Optional[str] = None
    id: Optional[str] = None
    validUntil: Optional[int] = None


class Data40(BaseModel):
    sessions: Optional[List[Session]] = None


class ListSessionsOfAuthorGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data40] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListSessionsOfAuthorGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListSessionsOfAuthorGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListSessionsOfAuthorGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data41(BaseModel):
    sessions: Optional[List[Session]] = None


class ListSessionsOfAuthorPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data41] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListSessionsOfAuthorPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListSessionsOfAuthorPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListSessionsOfAuthorPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data42(BaseModel):
    sessions: Optional[List[Session]] = None


class ListSessionsOfGroupGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data42] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListSessionsOfGroupGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListSessionsOfGroupGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListSessionsOfGroupGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data43(BaseModel):
    sessions: Optional[List[Session]] = None


class ListSessionsOfGroupPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data43] = None
    message: Optional[str] = Field(None, examples=['ok'])


class ListSessionsOfGroupPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class ListSessionsOfGroupPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class ListSessionsOfGroupPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class MovePadGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class MovePadGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class MovePadGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class MovePadGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class MovePadPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class MovePadPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class MovePadPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class MovePadPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class PadUser(BaseModel):
    colorId: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    timestamp: Optional[int] = None


class Data44(BaseModel):
    padUsers: Optional[List[PadUser]] = None


class PadUsersGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data44] = None
    message: Optional[str] = Field(None, examples=['ok'])


class PadUsersGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class PadUsersGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class PadUsersGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data45(BaseModel):
    padUsers: Optional[List[PadUser]] = None


class PadUsersPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data45] = None
    message: Optional[str] = Field(None, examples=['ok'])


class PadUsersPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class PadUsersPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class PadUsersPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class Data46(BaseModel):
    padUsersCount: Optional[int] = None


class PadUsersCountGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data46] = None
    message: Optional[str] = Field(None, examples=['ok'])


class PadUsersCountGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class PadUsersCountGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class PadUsersCountGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class PadUsersCountPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Data46] = None
    message: Optional[str] = Field(None, examples=['ok'])


class PadUsersCountPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class PadUsersCountPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class PadUsersCountPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class RestoreRevisionGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class RestoreRevisionGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class RestoreRevisionGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class RestoreRevisionGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class RestoreRevisionPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class RestoreRevisionPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class RestoreRevisionPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class RestoreRevisionPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SaveRevisionGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SaveRevisionGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SaveRevisionGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SaveRevisionGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SaveRevisionPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SaveRevisionPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SaveRevisionPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SaveRevisionPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SendClientsMessageGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SendClientsMessageGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SendClientsMessageGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SendClientsMessageGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SendClientsMessagePostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SendClientsMessagePostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SendClientsMessagePostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SendClientsMessagePostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SetHTMLGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SetHTMLGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SetHTMLGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SetHTMLGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SetHTMLPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SetHTMLPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SetHTMLPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SetHTMLPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SetPublicStatusGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SetPublicStatusGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SetPublicStatusGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SetPublicStatusGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SetPublicStatusPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SetPublicStatusPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SetPublicStatusPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SetPublicStatusPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SetTextGetResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SetTextGetResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SetTextGetResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SetTextGetResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])


class SetTextPostResponse(BaseModel):
    code: Optional[int] = Field(None, examples=[0])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['ok'])


class SetTextPostResponse1(BaseModel):
    code: Optional[int] = Field(None, examples=[1])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['error message'])


class SetTextPostResponse2(BaseModel):
    code: Optional[int] = Field(None, examples=[4])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['no or wrong API key'])


class SetTextPostResponse3(BaseModel):
    code: Optional[int] = Field(None, examples=[2])
    data: Optional[Dict[str, Any]] = Field(None, examples=[None])
    message: Optional[str] = Field(None, examples=['internal error'])
